const MATERIALS_KEY='edupath.demo.materials.v1';
function role(){return document.querySelector('.userbox small')?.textContent?.trim()||'';}
function lang(){return localStorage.getItem('edupath.language.v1')||'en';}
function esc(v:string){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
function ai(){return (window as any).EduPathAI;}
async function configured(){try{return Boolean((await ai()?.status?.())?.configured);}catch{return false;}}
function append(messages:HTMLElement,who:'user'|'ai',text:string){const d=document.createElement('div');d.className=`fx-message ${who}`;d.innerHTML=who==='ai'?`${esc(text)}<div class="fx-source">OpenAI response · role and page context enforced by EduPath</div>`:esc(text);messages.appendChild(d);messages.scrollTop=messages.scrollHeight;}

async function interceptStudent(form:HTMLFormElement){if(!(await configured()))return false;const page=form.closest<HTMLElement>('.learning-suite-page,.fx-page');if(!page)return false;const input=page.querySelector<HTMLTextAreaElement>('[data-input]');const q=input?.value.trim()||'';if(!q)return true;const grade=page.querySelector<HTMLSelectElement>('[data-grade]')?.value||'Selected grade';const subject=page.querySelector<HTMLSelectElement>('[data-subject]')?.value||'Selected subject';const messages=page.querySelector<HTMLElement>('.fx-messages');if(!messages)return false;append(messages,'user',q);if(input)input.value='';const loading=document.createElement('div');loading.className='fx-message ai';loading.textContent='Thinking…';messages.appendChild(loading);try{const prompt=`Act as Student GPT inside EduPath AI. Grade: ${grade}. Subject: ${subject}. Student question: ${q}. Teach step-by-step in the current interface language (${lang()}). Use teacher material and visible curriculum context when available. If an official curriculum source is not configured, say so clearly instead of inventing a source. For assessment-style questions, scaffold the method before the final answer.`;const reply=await ai().ask(prompt);loading.remove();append(messages,'ai',reply);void ai().speak(reply);}catch(error){loading.textContent=error instanceof Error?error.message:'Student GPT is temporarily unavailable.';}return true;}

async function interceptParent(form:HTMLFormElement){if(!(await configured()))return false;const page=form.closest<HTMLElement>('.fx-page');if(!page)return false;const input=page.querySelector<HTMLTextAreaElement>('[data-parent-input]');const q=input?.value.trim()||'';if(!q)return true;const messages=page.querySelector<HTMLElement>('.fx-messages');if(!messages)return false;append(messages,'user',q);if(input)input.value='';const loading=document.createElement('div');loading.className='fx-message ai';loading.textContent='Thinking…';messages.appendChild(loading);try{const visible=page.innerText.replace(/\s+/g,' ').slice(0,3500);const prompt=`Act as Parent GPT. Only use parent-visible information about the linked learner. Do not reveal confidential teacher notes, other learners, or restricted school data. Current parent-visible context: ${visible}. Parent question: ${q}. Give practical, supportive steps in the current interface language (${lang()}).`;const reply=await ai().ask(prompt);loading.remove();append(messages,'ai',reply);void ai().speak(reply);}catch(error){loading.textContent=error instanceof Error?error.message:'Parent GPT is temporarily unavailable.';}return true;}

async function interceptCopilot(button:HTMLElement){if(!(await configured()))return false;const page=button.closest<HTMLElement>('.fx-page');if(!page)return false;const grade=page.querySelector<HTMLSelectElement>('[data-grade]')?.value||'Grade 9';const subject=page.querySelector<HTMLSelectElement>('[data-subject]')?.value||'Mathematics';const task=page.querySelector<HTMLSelectElement>('[data-task]')?.value||'Lesson plan';const focus=page.querySelector<HTMLTextAreaElement>('[data-prompt]')?.value.trim()||'Core curriculum concept';const holder=page.querySelector<HTMLElement>('[data-output]');if(!holder)return false;holder.innerHTML='<p>Generating curriculum-aware draft…</p>';try{const prompt=`Act as Teacher Copilot. Prepare an editable ${task} for ${grade} ${subject}. Focus: ${focus}. Include learning intention, prerequisite knowledge, teacher modelling, guided practice, differentiated support, independent practice, formative assessment, common misconceptions, accessibility considerations and a short teacher review checklist. Do not claim the material is published or officially approved. Write in ${lang()}.`;const reply=await ai().ask(prompt);holder.innerHTML=`<span class="fx-chip">OpenAI-assisted draft · teacher review required</span><h3>${esc(task)} · ${esc(grade)} ${esc(subject)}</h3><div class="ai-copilot-text">${esc(reply).replace(/\n/g,'<br>')}</div><div class="fx-actions"><button type="button" class="fx-btn" data-ai-copy>Copy draft</button><button type="button" class="fx-btn primary" data-ai-save>Save as teacher material</button></div>`;holder.querySelector('[data-ai-copy]')?.addEventListener('click',()=>navigator.clipboard?.writeText(reply));holder.querySelector('[data-ai-save]')?.addEventListener('click',()=>{let list:any[]=[];try{list=JSON.parse(localStorage.getItem(MATERIALS_KEY)||'[]');}catch{}list.unshift({id:`openai-copilot-${Date.now()}`,title:`${task}: ${focus.slice(0,48)}`,grade,subject,type:'OpenAI Teacher Copilot draft',body:reply,published:false,createdAt:new Date().toISOString().slice(0,10)});localStorage.setItem(MATERIALS_KEY,JSON.stringify(list));holder.insertAdjacentHTML('beforeend','<p class="fx-source">Saved as an unpublished teacher resource. Review before publishing.</p>');});}catch(error){holder.innerHTML=`<p>${esc(error instanceof Error?error.message:'Teacher Copilot is temporarily unavailable.')}</p>`;}return true;}

document.addEventListener('submit',event=>{const form=event.target as HTMLFormElement;if(form.matches('[data-parent-form]')){void (async()=>{if(await configured()){event.preventDefault();event.stopImmediatePropagation();await interceptParent(form);}})();return;}if(form.matches('[data-form]')&&form.closest('[data-fx-student-gpt]')){void (async()=>{if(await configured()){event.preventDefault();event.stopImmediatePropagation();await interceptStudent(form);}})();}},true);
document.addEventListener('click',event=>{const button=(event.target as HTMLElement).closest<HTMLElement>('[data-generate]');if(!button||!button.closest('.fx-page'))return;void (async()=>{if(await configured()){event.preventDefault();event.stopImmediatePropagation();await interceptCopilot(button);}})();},true);
