type LanguageApi={languages:{code:string;label:string;native:string;bcp47:string}[];current:()=>{code:string;label:string;native:string;bcp47:string};setLanguage:(code:string)=>void;translate:(text:string,code?:string)=>string};

const DB_NAME='edupath-local-vault';
const DB_STORE='files';
const languageAliases:Record<string,string[]>={
  en:['english'],af:['afrikaans'],zu:['isizulu','zulu'],xh:['isixhosa','xhosa'],st:['sesotho','southern sotho'],tn:['setswana','tswana'],nso:['sepedi','northern sotho'],ts:['xitsonga','tsonga'],ve:['tshivenda','venda'],ss:['siswati','swati'],nr:['isindebele','ndebele']
};

function api():LanguageApi|undefined{return (window as any).EduPathI18n as LanguageApi|undefined;}
function detectLanguage(text:string){const t=text.toLowerCase();for(const [code,names] of Object.entries(languageAliases)){if(names.some(n=>t.includes(n))&&(t.includes('language')||t.includes('speak')||t.includes('explain')||t.includes('change')||t.includes('switch')||t.includes('ngolimi')||t.includes('puo')))return code;}return null;}
function syncFromChat(){document.addEventListener('click',e=>{const target=e.target as HTMLElement;const chat=target.closest('.chat');if(!chat)return;const input=chat.querySelector<HTMLInputElement>('input,textarea');const text=input?.value||target.textContent||'';const code=detectLanguage(text);if(code){api()?.setLanguage(code);setTimeout(()=>announceLanguage(code),20);}});document.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const target=e.target as HTMLInputElement;if(!target.closest?.('.chat'))return;const code=detectLanguage(target.value||'');if(code){api()?.setLanguage(code);setTimeout(()=>announceLanguage(code),20);}});}
function announceLanguage(code:string){const lang=api()?.languages.find(l=>l.code===code);if(!lang)return;const body=document.querySelector('.chat-body');if(body){const bubble=document.createElement('div');bubble.className='bubble ai';bubble.textContent=`Language changed to ${lang.native}. The website and Ayanda now share the same language preference.`;body.appendChild(bubble);body.scrollTop=body.scrollHeight;}}

function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(DB_STORE))db.createObjectStore(DB_STORE,{keyPath:'id'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function vaultPut(file:File,category:string){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put({id:`${Date.now()}-${file.name}`,name:file.name,type:file.type,size:file.size,category,createdAt:new Date().toISOString(),blob:file});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
async function vaultList(){const db=await openDb();return new Promise<any[]>((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readonly');const req=tx.objectStore(DB_STORE).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error);});}
async function vaultGet(id:string){const db=await openDb();return new Promise<any>((resolve,reject)=>{const req=db.transaction(DB_STORE,'readonly').objectStore(DB_STORE).get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function vaultDelete(id:string){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}

async function enhanceSovereignty(page:HTMLElement){if(page.dataset.vaultReady==='true')return;page.dataset.vaultReady='true';const body=page.querySelector('[data-wc-body]');if(!body)return;const section=document.createElement('section');section.className='wc-panel local-vault';section.innerHTML=`<div class="wc-section-head"><div><span class="vault-kicker">LOCAL DATA VAULT</span><h2>Keep sensitive exam files on this device</h2></div></div><p>Use IndexedDB-backed local storage for exam papers, answer books or other selected files. Files remain in this browser profile on this device unless you explicitly download or move them.</p><div class="vault-controls"><label>File category<select data-vault-category><option>Exam paper</option><option>Answer book</option><option>Study material</option><option>Other</option></select></label><label class="vault-upload">Choose local file<input type="file" data-vault-file /></label><button class="wc-btn primary" data-vault-save>Save locally</button></div><div data-vault-list class="vault-list"></div><p class="privacy-note">Local browser storage is not a substitute for institution-managed encryption, backup, endpoint security or retention controls in production.</p>`;body.appendChild(section);
  const draw=async()=>{const items=await vaultList();const holder=section.querySelector<HTMLElement>('[data-vault-list]')!;holder.innerHTML=items.length?items.map(x=>`<article><div><strong>${escapeHtml(x.name)}</strong><span>${escapeHtml(x.category)} · ${(x.size/1024).toFixed(1)} KB</span></div><small>${new Date(x.createdAt).toLocaleString()}</small><div><button data-vault-open="${x.id}">Open</button><button data-vault-delete="${x.id}">Delete</button></div></article>`).join(''):'<p>No local files stored yet.</p>';holder.querySelectorAll<HTMLElement>('[data-vault-open]').forEach(b=>b.addEventListener('click',async()=>{const item=await vaultGet(b.dataset.vaultOpen||'');if(!item)return;const url=URL.createObjectURL(item.blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);}));holder.querySelectorAll<HTMLElement>('[data-vault-delete]').forEach(b=>b.addEventListener('click',async()=>{await vaultDelete(b.dataset.vaultDelete||'');draw();}));};
  section.querySelector('[data-vault-save]')?.addEventListener('click',async()=>{const input=section.querySelector<HTMLInputElement>('[data-vault-file]')!;if(!input.files?.[0])return;const category=(section.querySelector('[data-vault-category]') as HTMLSelectElement).value;await vaultPut(input.files[0],category);input.value='';draw();});draw();}

function enhanceStudentDetail(root:ParentNode=document){root.querySelectorAll<HTMLElement>('.student-detail').forEach(detail=>{if(detail.dataset.hardened==='true')return;detail.dataset.hardened='true';const ensurePanel=(key:string,title:string,html:string)=>{let p=detail.querySelector<HTMLElement>(`[data-${key}-panel]`);if(!p){p=document.createElement('div');p.className='wc-expand';p.dataset[`${key}Panel`]='true';p.hidden=true;p.innerHTML=`<h4>${title}</h4>${html}`;detail.appendChild(p);}return p;};detail.querySelector('[data-expand-support]')?.addEventListener('click',()=>{const p=ensurePanel('support','Support history','<p>Demo support history: geometry remediation active; next review scheduled; all consequential updates require authorised educator approval.</p>');p.hidden=!p.hidden;});detail.querySelector('[data-expand-guardian]')?.addEventListener('click',()=>{const p=ensurePanel('guardian','Guardian access','<p>Guardian access is relationship-scoped and excludes confidential educator notes, other learners and administrative records.</p>');p.hidden=!p.hidden;});});}

function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
function watch(){const observer=new MutationObserver(()=>{const page=document.querySelector<HTMLElement>('[data-wc-page="sovereignty"]:not([hidden])');if(page)enhanceSovereignty(page);enhanceStudentDetail();});observer.observe(document.body,{childList:true,subtree:true});enhanceStudentDetail();}

syncFromChat();watch();
