import {detail,esc} from './experience-core';

const KEY='edupath.career.progress.v2';
const courses=[
{id:'discover',title:'Career Discovery & Pathway Planning',aud:'All school leavers',hours:6,badge:'Career Explorer',mods:['Discover strengths and interests','Explore occupations and growth sectors','Compare university, TVET, learnership and work pathways','Build a 12-month transition plan']},
{id:'digital',title:'Digital Workplace Foundations',aud:'All school leavers',hours:10,badge:'Digital Workplace Ready',mods:['Professional digital identity','Documents, spreadsheets and presentations','Email, calendars and collaboration','Cybersecurity and privacy basics','Responsible AI at work']},
{id:'employ',title:'CV, Interview & Personal Brand',aud:'Employment readiness',hours:8,badge:'Job Search Ready',mods:['Build an evidence-based CV','Write targeted applications','Prepare for competency interviews','Create a professional online profile','Practise workplace communication']},
{id:'ai',title:'AI & Data Literacy for Work',aud:'Future workforce',hours:12,badge:'AI & Data Foundations',mods:['Understand AI and automation','Read and communicate with data','Use generative AI responsibly','Verify AI outputs and sources','Apply AI to workplace tasks']},
{id:'corporate',title:'Corporate Readiness',aud:'Private sector',hours:9,badge:'Corporate Ready',mods:['Workplace expectations and culture','Team collaboration','Project and task management','Customer experience','Performance and continuous learning']},
{id:'public',title:'Public Sector Digital Literacy',aud:'Government',hours:9,badge:'Digital Public Service',mods:['Citizen-centred digital services','Information governance','Privacy and security','Responsible AI in government','Audit-ready digital work']},
{id:'sme',title:'SME & Entrepreneurship',aud:'Entrepreneurship',hours:12,badge:'Digital Entrepreneur',mods:['Validate a business idea','Build a business model','Digital marketing and commerce','Cash flow basics','AI tools for small business','Cyber safety for SMEs']},
{id:'portfolio',title:'Workplace Project & Portfolio',aud:'Evidence of capability',hours:15,badge:'Workplace Portfolio',mods:['Choose a real-world problem','Plan a small project','Build and document the solution','Present the outcome','Reflect and capture evidence']}
];

function render(page:HTMLElement){let progress:Record<string,number>={};try{progress=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{}const draw=()=>{page.innerHTML=`<div class="fx-inner" data-fx-career><div class="fx-head"><div><span class="fx-kicker">POST-SCHOOL TRANSITION</span><h1>Career Readiness & Workplace Services</h1><p>A structured bridge from school to university, TVET, learnerships, employment, public service and entrepreneurship.</p></div><button class="fx-btn" data-wc-back>Back to workspace</button></div><section class="fx-panel" style="margin-bottom:16px;background:linear-gradient(120deg,#17254a,#3657dc);color:#fff"><span class="fx-kicker" style="color:#c7d2ff">AI-POWERED INDUSTRY TRAINING ENGINE</span><h2>Discover → Learn → Practise → Prove skills → Prepare for work</h2><p style="color:#e0e6ff">Learners earn badges and build a portable skills portfolio.</p></section><section class="fx-card-grid">${courses.map(c=>{const p=progress[c.id]||0;return`<article class="fx-card"><span class="fx-chip">${esc(c.aud)}</span><h3>${esc(c.title)}</h3><p>${c.hours} guided hours · Badge: ${esc(c.badge)}</p><div class="fx-progress"><i style="width:${p}%"></i></div><small>${p}% complete</small><div class="fx-actions"><button class="fx-btn" data-course="${c.id}">View course</button><button class="fx-btn primary" data-next="${c.id}">${p?'Continue':'Start'}</button></div></article>`}).join('')}</section><section class="fx-panel" style="margin-top:16px"><h2>Employment-readiness evidence</h2><div class="fx-detail-stats"><article><strong>${courses.filter(c=>(progress[c.id]||0)>=100).length}</strong><span>Badges completed</span></article><article><strong>${Math.round(Object.values(progress).reduce((a,b)=>a+b,0)/courses.length)||0}%</strong><span>Overall progress</span></article><article><strong>Portfolio</strong><span>Projects and evidence</span></article><article><strong>Human + AI</strong><span>Coached transition planning</span></article></div></section></div>`;page.querySelectorAll<HTMLElement>('[data-course]').forEach(b=>b.addEventListener('click',()=>{const c=courses.find(x=>x.id===b.dataset.course);if(c)detail(c.title,`${c.hours} guided hours. Earn the ${c.badge} badge after completing modules and evidence requirements.`,c.mods.map(x=>`Module: ${x}`));}));page.querySelectorAll<HTMLElement>('[data-next]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.next||'';progress[id]=Math.min(100,(progress[id]||0)+20);localStorage.setItem(KEY,JSON.stringify(progress));draw();}));};draw();}

function upgrade(){const page=document.querySelector<HTMLElement>('.wc-page:not([hidden])');if(page?.dataset.wcPage==='career'&&!page.querySelector('[data-fx-career]'))render(page);}
let pending=false;const schedule=()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;upgrade();});};new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
