type AttrKey='placeholder'|'title'|'aria-label';
type Target={kind:'text'|'attr'|'option';node:Text|HTMLElement;attr?:AttrKey;source:string};

const LANG_KEY='edupath.language.v1';
const SUPPORTED_CODES=['en','af','zu','xh','st','tn','nso','ts','ve','ss','nr'];
const textSource=new WeakMap<Text,string>();
const attrSource=new WeakMap<HTMLElement,Map<string,string>>();
const optionSource=new WeakMap<HTMLOptionElement,{text:string;value:string}>();
let translating=false;
let pending=false;
let rerun=false;
let lastFailure=0;

function code(){return localStorage.getItem(LANG_KEY)||'en';}
function languageName(c:string){return ({en:'English',af:'Afrikaans',zu:'isiZulu',xh:'isiXhosa',st:'Sesotho',tn:'Setswana',nso:'Sepedi',ts:'itsonga',ve:'Tshivenda',ss:'siSwati',nr:'isiNdebele'} as Record<string,string>)[c]||c;}
function cacheKey(c:string){return `edupath.full-i18n.${c}.v2`;}
function loadCache(c:string){try{return JSON.parse(localStorage.getItem(cacheKey(c))||'{}') as Record<string,string>;}catch{return{};}}
function saveCache(c:string,cache:Record<string,string>){try{const entries=Object.entries(cache);if(entries.length>1800){const trimmed=Object.fromEntries(entries.slice(entries.length-1500));localStorage.setItem(cacheKey(c),JSON.stringify(trimmed));}else localStorage.setItem(cacheKey(c),JSON.stringify(cache));}catch{}}
function apiHeaders(){return {'Content-Type':'application/json','x-edupath-role':document.querySelector('.userbox small')?.textContent?.trim()||'','x-edupath-actor':document.querySelector('.userbox strong')?.textContent?.trim()||'Demo User'};}
function shouldSkip(el:Element|null){if(!el)return true;if(el.closest('[data-no-i18n],script,style,code,pre,.ai-toast'))return true;if(el.closest('.language-picker select,.ai-voice-picker select'))return true;return false;}
function sourceForText(node:Text){if(!textSource.has(node))textSource.set(node,(node.textContent||'').trim());return textSource.get(node)||'';}
function sourceForAttr(el:HTMLElement,attr:AttrKey){let m=attrSource.get(el);if(!m){m=new Map();attrSource.set(el,m);}if(!m.has(attr))m.set(attr,el.getAttribute(attr)||'');return m.get(attr)||'';}
function sourceForOption(option:HTMLOptionElement){if(!optionSource.has(option)){const original={text:option.textContent?.trim()||'',value:option.value};optionSource.set(option,original);option.value=original.value;}return optionSource.get(option)!;}
function meaningful(s:string){const v=s.trim();if(!v)return false;if(/^[-+]?\d+(?:[.,]\d+)?%?$/.test(v))return false;if(/^(https?:\/\/|mailto:|[\w.-]+@[\w.-]+\.)/i.test(v))return false;if(v.length>900)return false;return /[A-Za-zÀ-ž]/.test(v);}
function collect(root:ParentNode=document){const out:Target[]=[];const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(shouldSkip(p))return NodeFilter.FILTER_REJECT;const s=sourceForText(n as Text);return meaningful(s)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;}});let n:Node|null;while((n=walker.nextNode()))out.push({kind:'text',node:n as Text,source:sourceForText(n as Text)});
  root.querySelectorAll?.<HTMLElement>('[placeholder],[title],[aria-label]').forEach(el=>{if(shouldSkip(el))return;(['placeholder','title','aria-label'] as AttrKey[]).forEach(attr=>{if(el.hasAttribute(attr)){const s=sourceForAttr(el,attr);if(meaningful(s))out.push({kind:'attr',node:el,attr,source:s});}});});
  root.querySelectorAll?.<HTMLOptionElement>('option').forEach(option=>{if(shouldSkip(option))return;const original=sourceForOption(option);if(meaningful(original.text))out.push({kind:'option',node:option,source:original.text});});
  return out;
}
function apply(target:Target,value:string){if(target.kind==='text')(target.node as Text).textContent=value;else if(target.kind==='attr')(target.node as HTMLElement).setAttribute(target.attr!,value);else{const option=target.node as HTMLOptionElement;const original=sourceForOption(option);option.value=original.value;option.textContent=value;}}
function restoreEnglish(root:ParentNode=document){collect(root).forEach(t=>apply(t,t.source));document.documentElement.lang='en-ZA';}
function overlay(show:boolean,label=''){let el=document.querySelector<HTMLElement>('.full-i18n-overlay');if(show){if(!el){el=document.createElement('div');el.className='full-i18n-overlay';el.dataset.noI18n='true';document.body.appendChild(el);}el.innerHTML=`<div><span class="full-i18n-spinner"></span><strong>Translating the complete interface to ${label}…</strong><small>Navigation, pages, dialogs and dynamic content are being synchronised.</small></div>`;el.hidden=false;}else if(el)el.hidden=true;}
async function translateBatch(items:string[],targetCode:string){const response=await fetch('/api/ai/translate',{method:'POST',headers:apiHeaders(),body:JSON.stringify({language:targetCode,items})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||'Interface translation failed.');return data.translations as string[];}
async function translateAll(root:ParentNode=document,showOverlay=true){const targetCode=code();if(targetCode==='en'){restoreEnglish(root);overlay(false);return;}if(translating){rerun=true;return;}translating=true;if(showOverlay)overlay(true,languageName(targetCode));try{const targets=collect(root);const cache=loadCache(targetCode);const unique=[...new Set(targets.map(t=>t.source))];const missing=unique.filter(s=>!cache[s]);for(let i=0;i<missing.length;i+=55){const batch=missing.slice(i,i+55);const translated=await translateBatch(batch,targetCode);batch.forEach((source,index)=>{if(translated[index])cache[source]=translated[index];});saveCache(targetCode,cache);}targets.forEach(t=>apply(t,cache[t.source]||t.source));document.documentElement.lang=({af:'af-ZA',zu:'zu-ZA',xh:'xh-ZA',st:'st-ZA',tn:'tn-ZA',nso:'nso-ZA',ts:'ts-ZA',ve:'ve-ZA',ss:'ss-ZA',nr:'nr-ZA'} as Record<string,string>)[targetCode]||targetCode;window.dispatchEvent(new CustomEvent('edupath:fulltranslation',{detail:{language:targetCode,count:targets.length}}));}catch(error){console.warn('Full interface translation unavailable',error);if(Date.now()-lastFailure>12000){lastFailure=Date.now();let banner=document.querySelector<HTMLElement>('.full-i18n-warning');if(!banner){banner=document.createElement('div');banner.className='full-i18n-warning';banner.dataset.noI18n='true';document.body.appendChild(banner);}banner.textContent=error instanceof Error?`${error.message} Configure OpenAI in Platform Administrator → AI & Voice Settings for complete localisation.`:'Complete localisation is unavailable.';setTimeout(()=>banner?.remove(),6000);}}finally{translating=false;overlay(false);if(rerun){rerun=false;void translateAll(document,false);}}}
function schedule(root:ParentNode=document){if(code()==='en')return;if(pending)return;pending=true;window.setTimeout(()=>{pending=false;void translateAll(root,false);},90);}

window.addEventListener('edupath:languagechange',()=>void translateAll(document,true));window.addEventListener('edupath:ai-configured',()=>{if(code()!=='en')void translateAll(document,true);});
const observer=new MutationObserver(mutations=>{if(code()==='en')return;const roots:HTMLElement[]=[];for(const m of mutations)m.addedNodes.forEach(n=>{if(n instanceof HTMLElement&&!n.closest('[data-no-i18n]'))roots.push(n);});if(roots.length)schedule(document);});observer.observe(document.body,{childList:true,subtree:true});
const style=document.createElement('style');style.textContent=`.full-i18n-overlay{position:fixed;inset:0;z-index:99998;background:rgba(245,248,253,.94);display:grid;place-items:center;backdrop-filter:blur(6px)}.full-i18n-overlay[hidden]{display:none}.full-i18n-overlay>div{display:grid;justify-items:center;gap:10px;color:#0c1939;text-align:center;padding:28px}.full-i18n-overlay small{color:#65728d}.full-i18n-spinner{width:34px;height:34px;border:4px solid #d8e1f3;border-top-color:#4d5cff;border-radius:50%;animation:fullspin .8s linear infinite}.full-i18n-warning{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:99999;max-width:760px;background:#7a2e0e;color:#fff;padding:12px 16px;border-radius:12px;box-shadow:0 12px 30px rgba(0,0,0,.18);font-size:13px}@keyframes fullspin{to{transform:rotate(360deg)}}`;document.head.appendChild(style);

if(code()!=='en')window.setTimeout(()=>void translateAll(document,true),180);(window as any).EduPathFullI18n={translate:translateAll,clearCache:(c?:string)=>{if(c)localStorage.removeItem(cacheKey(c));else SUPPORTED_CODES.forEach(k=>localStorage.removeItem(cacheKey(k)));}};
