import './navigation-stability.css';

type Role='Learner'|'Teacher'|'Parent / Guardian'|'Principal / School Administrator'|'District Official'|'Provincial Official'|'National Education Analyst'|'Platform Administrator'|'Support Administrator';
type DetailModel={title:string;summary:string;facts:string[];actions:string[]};

type AiApi={status?:()=>Promise<{configured?:boolean}|null>;ask?:(message:string)=>Promise<string>;speak?:(text:string)=>Promise<void>|void;stop?:()=>void};

const ROLE_KEY='edupath.role.stable.v1';
const ROLES:Role[]=['Learner','Teacher','Parent / Guardian','Principal / School Administrator','District Official','Provincial Official','National Education Analyst','Platform Administrator','Support Administrator'];
const GRADES=['Grade R','Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6','Grade 7','Grade 8','Grade 9','Grade 10','Grade 11','Grade 12'];
const FOUNDATION=['Home Language','First Additional Language','Mathematics','Life Skills'];
const INTERMEDIATE=['Home Language','First Additional Language','Mathematics','Natural Sciences and Technology','Social Sciences','Life Skills'];
const SENIOR=['Home Language','First Additional Language','Mathematics','Natural Sciences','Social Sciences','Technology','Economic and Management Sciences','Creative Arts','Life Orientation'];
const FET=['Home Language','First Additional Language','Mathematics','Mathematical Literacy','Life Orientation','Physical Sciences','Life Sciences','Geography','History','Accounting','Business Studies','Economics','Agricultural Sciences','Agricultural Management Practices','Agricultural Technology','Civil Technology','Electrical Technology','Mechanical Technology','Engineering Graphics and Design','Computer Applications Technology','Information Technology','Tourism','Hospitality Studies','Consumer Studies','Design','Dance Studies','Dramatic Arts','Music','Visual Arts','Religion Studies','Marine Sciences','Technical Mathematics','Technical Sciences'];
const NAV_KEYS=['Overview','My Learning','Subjects','Assignments','Assessments','Results','Classes','Learners','Interventions','Attendance','Teacher Copilot','Progress','Messages','Teachers','Academic Progress','Digital Inclusion','Schools','Districts','Reports','National Analytics','Users','Roles','Curriculum','Audit Log','System Health','Support Cases','Student GPT','Learning Hub','Training Academy','Exam Practice','Curriculum R–12','Proctored Exams','Student Management','Career Readiness','Reports & User Logs','Security & Data Sovereignty','Agent Centre','Parent GPT','AI & Voice Settings'];

const child={name:'Thando Mokoena',grade:'Grade 9',school:'EduPath Demo High School',subjects:[
  {name:'Mathematics',score:71,status:'Improving',challenge:'Geometry and angle relationships',support:'Use prerequisite revision on parallel lines, worked examples and a short teacher-reviewed formative check.'},
  {name:'English Home Language',score:78,status:'On track',challenge:'Essay structure and use of evidence',support:'Use a paragraph-planning scaffold and the teacher feedback checklist.'},
  {name:'First Additional Language',score:75,status:'On track',challenge:'Vocabulary in extended writing',support:'Use regular reading, vocabulary retrieval and short writing practice.'},
  {name:'Natural Sciences',score:74,status:'On track',challenge:'Explaining energy transfer',support:'Use a concept map and retrieval questions before the next task.'},
  {name:'Social Sciences',score:72,status:'On track',challenge:'Source interpretation',support:'Use origin-purpose-context-evidence prompts when analysing a source.'},
  {name:'Technology',score:70,status:'Review',challenge:'Design-process documentation',support:'Use a structured design brief and rubric walkthrough.'},
  {name:'Economic and Management Sciences',score:73,status:'On track',challenge:'Financial literacy application',support:'Use worked budgeting examples and a terminology glossary.'},
  {name:'Creative Arts',score:81,status:'Strong',challenge:'Portfolio reflection',support:'Use reflection prompts to explain choices and development.'},
  {name:'Life Orientation',score:84,status:'Strong',challenge:'Career pathway planning',support:'Continue the Career Readiness pathway and subject-choice exploration.'}
]};

function esc(v:string){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
function ai():AiApi|undefined{return (window as any).EduPathAI as AiApi|undefined;}
function subjectsForGrade(g:string){const n=g==='Grade R'?0:Number(g.replace(/\D/g,''));return n<=3?FOUNDATION:n<=6?INTERMEDIATE:n<=9?SENIOR:FET;}
function currentLanguage(){return localStorage.getItem('edupath.language.v1')||'en';}
function cleanNavText(v:string){return v.replace(/[✦◎◉]/g,'').replace(/\s+\d+$/,'').replace(/\s+/g,' ').trim();}
function roleElement(){return document.querySelector<HTMLElement>('.userbox small');}
function currentRole():Role{
  const el=roleElement();
  const data=el?.dataset.roleKey as Role|undefined;
  if(data&&ROLES.includes(data))return data;
  const saved=localStorage.getItem(ROLE_KEY) as Role|null;
  if(saved&&ROLES.includes(saved))return saved;
  const text=el?.textContent?.trim() as Role|undefined;
  return text&&ROLES.includes(text)?text:'Learner';
}
function stabilizeRole(){
  const el=roleElement();if(!el)return;
  let value=(el.dataset.roleKey||el.textContent?.trim()||localStorage.getItem(ROLE_KEY)||'') as Role;
  if(!ROLES.includes(value)){const saved=localStorage.getItem(ROLE_KEY) as Role|null;if(saved&&ROLES.includes(saved))value=saved;}
  if(!ROLES.includes(value))return;
  el.dataset.roleKey=value;
  el.dataset.noI18n='role-key';
  localStorage.setItem(ROLE_KEY,value);
}
function assignNavKeys(){
  document.querySelectorAll<HTMLButtonElement>('.app-shell aside button').forEach(button=>{
    if(button.dataset.navKey)return;
    const text=cleanNavText(button.textContent||'');
    const exact=NAV_KEYS.find(k=>text===k||text.endsWith(k));
    if(exact)button.dataset.navKey=exact;
  });
}
function buttonFor(key:string){assignNavKeys();return [...document.querySelectorAll<HTMLButtonElement>('.app-shell aside button')].find(b=>b.dataset.navKey===key||cleanNavText(b.textContent||'')===key);}
function dedupe(selector:string){
  const nodes=[...document.querySelectorAll<HTMLElement>(selector)];if(nodes.length<=1)return;
  const keep=nodes.find(n=>!n.hidden&&n.offsetParent!==null)||nodes[nodes.length-1];
  nodes.forEach(n=>{if(n!==keep)n.remove();});
}
function dedupeDynamicPages(){
  dedupe('.learning-suite-page');
  dedupe('.exam-practice-page');
  dedupe('.agent-centre-page');
  dedupe('.ai-settings-page');
}
function resetWorkspace(except?:HTMLElement){
  const shell=document.querySelector<HTMLElement>('.app-shell');
  if(!shell)return;
  shell.querySelectorAll<HTMLElement>('.learning-suite-page,.exam-practice-page,.agent-centre-page,.wc-page,.fx-page,.ai-settings-page,.commercial-feature-page').forEach(page=>{if(page!==except)page.hidden=true;});
  document.querySelectorAll<HTMLElement>('.fx-drawer,.commercial-detail-drawer').forEach(d=>d.classList.remove('open'));
  const main=shell.querySelector<HTMLElement>('main');if(main&&main!==except){main.hidden=false;main.style.display='block';}
}
function ensureFeaturePage(id:string){
  const shell=document.querySelector<HTMLElement>('.app-shell');if(!shell)return null;
  let page=shell.querySelector<HTMLElement>(`.commercial-feature-page[data-commercial-feature="${id}"]`);
  if(!page){page=document.createElement('section');page.className='commercial-feature-page';page.dataset.commercialFeature=id;page.hidden=true;shell.appendChild(page);}
  return page;
}
function openFeature(id:'student-gpt'|'parent-gpt'|'teacher-copilot'){
  const page=ensureFeaturePage(id);const shell=document.querySelector<HTMLElement>('.app-shell');const main=shell?.querySelector<HTMLElement>('main');if(!page||!main)return;
  resetWorkspace(page);main.hidden=true;main.style.display='none';page.hidden=false;
  if(id==='student-gpt')renderStudentGpt(page);
  if(id==='parent-gpt')renderParentGpt(page);
  if(id==='teacher-copilot')renderTeacherCopilot(page);
  window.scrollTo({top:0,behavior:'smooth'});
}
function backToWorkspace(){
  resetWorkspace();
  const overview=buttonFor('Overview');if(overview)overview.click();
}
async function openAIConfigured(){try{return Boolean((await ai()?.status?.())?.configured);}catch{return false;}}
async function askAI(prompt:string){if(!(await openAIConfigured())||!ai()?.ask)throw new Error('OpenAI is not configured.');return ai()!.ask!(prompt);}
function speak(text:string){try{void ai()?.speak?.(text);}catch{/* voice is optional */}}

function renderStudentGpt(page:HTMLElement){
  let grade=child.grade;let subject='Mathematics';const messages:{who:'user'|'ai';text:string}[]=[{who:'ai',text:'Student GPT is ready. Select any configured grade and subject, then ask for an explanation, worked example, practice question or revision support.'}];
  const draw=()=>{
    const subs=subjectsForGrade(grade);if(!subs.includes(subject))subject=subs[0];
    page.innerHTML=`<div class="commercial-feature-inner"><div class="commercial-feature-head"><div><span class="commercial-kicker">CURRICULUM-GROUNDED STUDENT SUPPORT</span><h1>Student GPT</h1><p>Grade R–12 assistance across the configured South African subject catalogue. EduPath keeps the selected grade and subject context explicit and separates AI guidance from official teacher or curriculum authority.</p></div><button class="commercial-btn" data-commercial-back>Back to workspace</button></div><div class="commercial-grid"><section class="commercial-panel"><div class="commercial-toolbar"><label>Grade<select data-grade>${GRADES.map(g=>`<option ${g===grade?'selected':''}>${esc(g)}</option>`).join('')}</select></label><label>Subject<select data-subject>${subs.map(s=>`<option ${s===subject?'selected':''}>${esc(s)}</option>`).join('')}</select></label><span class="commercial-kicker">${esc(currentLanguage().toUpperCase())} · OPENAI WHEN CONFIGURED</span></div><div class="commercial-messages" data-messages>${messages.map(m=>`<div class="commercial-message ${m.who}">${esc(m.text)}</div>`).join('')}</div><form class="commercial-chat-form" data-form><textarea data-input required placeholder="Ask a ${esc(grade)} ${esc(subject)} question…"></textarea><button class="commercial-btn primary" type="submit">Ask Student GPT</button></form></section><aside class="commercial-panel dark"><span class="commercial-kicker">LEARNING CONTEXT</span><h2>${esc(grade)} · ${esc(subject)}</h2><p>Student GPT can explain concepts, scaffold problem solving, create practice questions, identify prerequisite gaps and suggest revision steps.</p><div class="commercial-info-list"><div><small>Grounding</small><strong>Selected grade + subject + visible EduPath context</strong></div><div><small>Safety</small><strong>No fabricated official source or autonomous high-stakes decision</strong></div><div><small>Teaching method</small><strong>Concept → worked example → learner attempt → self-check</strong></div></div><div class="commercial-toolbar" style="margin-top:18px"><button class="commercial-btn" data-prompt="Explain the main concepts I should know in this subject.">Explain key concepts</button><button class="commercial-btn" data-prompt="Give me a worked example and then a similar question to try myself.">Worked example</button><button class="commercial-btn" data-prompt="Help me identify prerequisite gaps before I continue.">Check prerequisites</button></div></aside></div></div>`;
    page.querySelector('[data-commercial-back]')?.addEventListener('click',backToWorkspace);
    page.querySelector<HTMLSelectElement>('[data-grade]')?.addEventListener('change',e=>{grade=(e.target as HTMLSelectElement).value;subject=subjectsForGrade(grade)[0];draw();});
    page.querySelector<HTMLSelectElement>('[data-subject]')?.addEventListener('change',e=>{subject=(e.target as HTMLSelectElement).value;draw();});
    page.querySelectorAll<HTMLButtonElement>('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{const input=page.querySelector<HTMLTextAreaElement>('[data-input]');if(input){input.value=b.dataset.prompt||'';input.focus();}}));
    page.querySelector<HTMLFormElement>('[data-form]')?.addEventListener('submit',async e=>{e.preventDefault();const input=page.querySelector<HTMLTextAreaElement>('[data-input]');const q=input?.value.trim()||'';if(!q)return;messages.push({who:'user',text:q});messages.push({who:'ai',text:'Thinking…'});draw();try{const prompt=`You are Student GPT inside EduPath AI. Learner context: ${grade}, ${subject}. Interface language code: ${currentLanguage()}. Question: ${q}. Teach step-by-step. Begin with the concept, show a worked example where useful, ask a short self-check question, and suggest the next learning step. If an official curriculum source is not present in the supplied context, say that clearly rather than inventing a citation. Do not make high-stakes academic decisions.`;const reply=await askAI(prompt);messages[messages.length-1]={who:'ai',text:reply};draw();speak(reply);}catch{const topics=subject==='Mathematics'?'number operations, algebra, geometry, measurement, data handling and probability':subject.includes('Language')?'listening and speaking, reading and viewing, writing and presenting, and language structures':subject.includes('Science')?'scientific concepts, evidence, investigation, application and explanation':'core concepts, source/evidence use, application, assessment practice and progression';const reply=`For ${grade} ${subject}, start by identifying the exact skill being assessed. Break the task into: 1) identify the concept, 2) state the relevant rule or evidence, 3) apply it step-by-step, and 4) check the result against the question. Typical focus areas include ${topics}. OpenAI is not currently available, so this response is the governed EduPath fallback rather than a generated curriculum answer.`;messages[messages.length-1]={who:'ai',text:reply};draw();}});
  };draw();
}

function renderParentGpt(page:HTMLElement){
  const messages:{who:'user'|'ai';text:string}[]=[{who:'ai',text:`Parent GPT is ready to explain ${child.name}'s parent-visible progress, current challenges and practical ways to help at home.`}];
  const draw=()=>{
    page.innerHTML=`<div class="commercial-feature-inner"><div class="commercial-feature-head"><div><span class="commercial-kicker">PARENT / GUARDIAN SUPPORT</span><h1>Parent GPT</h1><p>Permission-filtered guidance using only information that a linked parent or guardian is authorised to see.</p></div><button class="commercial-btn" data-commercial-back>Back to workspace</button></div><div class="commercial-grid"><section class="commercial-panel"><div class="commercial-messages">${messages.map(m=>`<div class="commercial-message ${m.who}">${esc(m.text)}</div>`).join('')}</div><form class="commercial-chat-form" data-parent-form><textarea data-parent-input required placeholder="Ask about progress, challenges, assignments or how you can help…"></textarea><button class="commercial-btn primary" type="submit">Ask Parent GPT</button></form></section><aside class="commercial-panel dark"><span class="commercial-kicker">LINKED LEARNER</span><h2>${esc(child.name)}</h2><p>${esc(child.grade)} · ${esc(child.school)}</p><div class="commercial-info-list"><div><small>Current priority</small><strong>Mathematics geometry and angle relationships</strong></div><div><small>Attendance</small><strong>94% demo record</strong></div><div><small>Privacy boundary</small><strong>No confidential teacher notes or other learner records</strong></div></div></aside></div><section class="commercial-panel" style="margin-top:18px"><span class="commercial-kicker">SUBJECT VIEW</span><h2>How the learner is progressing</h2><div class="commercial-subjects">${child.subjects.map(s=>`<article class="commercial-subject-card"><header><strong>${esc(s.name)}</strong><span>${s.score}% · ${esc(s.status)}</span></header><div class="commercial-progress"><i style="width:${s.score}%"></i></div><p><b>Current challenge:</b> ${esc(s.challenge)}</p><p><b>How you can help:</b> ${esc(s.support)}</p></article>`).join('')}</div></section></div>`;
    page.querySelector('[data-commercial-back]')?.addEventListener('click',backToWorkspace);
    page.querySelector<HTMLFormElement>('[data-parent-form]')?.addEventListener('submit',async e=>{e.preventDefault();const input=page.querySelector<HTMLTextAreaElement>('[data-parent-input]');const q=input?.value.trim()||'';if(!q)return;messages.push({who:'user',text:q});messages.push({who:'ai',text:'Thinking…'});draw();try{const visible=child.subjects.map(s=>`${s.name}: ${s.score}%, ${s.status}; challenge=${s.challenge}; support=${s.support}`).join(' | ');const prompt=`You are Parent GPT inside EduPath AI. Use only this parent-visible information for ${child.name}: ${visible}. Attendance: 94%. Parent question: ${q}. Give a concise, practical answer in interface language code ${currentLanguage()}. Never expose confidential teacher notes, restricted records or information about other learners.`;const reply=await askAI(prompt);messages[messages.length-1]={who:'ai',text:reply};draw();speak(reply);}catch{const low=q.toLowerCase();let reply=`${child.name} is broadly on track. The current priority is Mathematics geometry. The most useful support is short, regular revision, asking the learner to explain the rule aloud, and using teacher-provided examples before another formative check.`;if(low.includes('subject'))reply=`The linked learner's current subjects are ${child.subjects.map(s=>s.name).join(', ')}.`;if(low.includes('attendance'))reply='Attendance is 94% in the demo record. EduPath uses attendance as a support signal and does not infer sensitive reasons for absence.';messages[messages.length-1]={who:'ai',text:reply};draw();}});
  };draw();
}

function copilotFallback(task:string,grade:string,subject:string,focus:string){return `${task} · ${grade} ${subject}\n\nLearning intention\nLearners will demonstrate understanding of ${focus} using the selected curriculum context.\n\nPrerequisite check\nConfirm prior knowledge and surface misconceptions before introducing new material.\n\nTeacher modelling\nExplain the concept explicitly, model one worked example and verbalise the reasoning process.\n\nGuided practice\nUse two scaffolded examples with prompts, paired explanation and immediate feedback.\n\nDifferentiation\nProvide vocabulary support, a visual scaffold and an extension task for learners ready to progress.\n\nIndependent practice\nLearners complete a short task individually and show evidence of method or reasoning.\n\nFormative assessment\nUse an exit question, capture common misconceptions and identify learners requiring remediation.\n\nTeacher review checklist\nCheck curriculum fit, factual accuracy, accessibility, assessment quality and suitability before publishing.`;}
function renderTeacherCopilot(page:HTMLElement){
  let grade='Grade 9';let subject='Mathematics';
  const draw=()=>{const subs=subjectsForGrade(grade);if(!subs.includes(subject))subject=subs[0];page.innerHTML=`<div class="commercial-feature-inner"><div class="commercial-feature-head"><div><span class="commercial-kicker">AI-ASSISTED TEACHING</span><h1>Teacher Copilot</h1><p>Create editable lesson plans, formative assessments, remediation activities, differentiated tasks and parent-friendly summaries. The demo school is configured as a high school, so this workspace is scoped to Grades 8–12.</p></div><button class="commercial-btn" data-commercial-back>Back to workspace</button></div><div class="commercial-grid"><section class="commercial-panel"><form class="commercial-form" data-copilot-form><div class="commercial-toolbar"><label>Grade<select data-grade>${['Grade 8','Grade 9','Grade 10','Grade 11','Grade 12'].map(g=>`<option ${g===grade?'selected':''}>${g}</option>`).join('')}</select></label><label>Subject<select data-subject>${subs.map(s=>`<option ${s===subject?'selected':''}>${esc(s)}</option>`).join('')}</select></label><label>Task<select data-task><option>Lesson plan</option><option>Formative assessment</option><option>Remediation activity</option><option>Differentiated activity</option><option>Revision pack</option><option>Parent-friendly progress summary</option></select></label></div><label>Learning focus<textarea data-focus required placeholder="Describe the topic, outcome, misconception or learner need…">Corresponding and alternate angles on parallel lines</textarea></label><button class="commercial-btn primary" type="submit">Generate editable draft</button></form><div class="commercial-output" data-output>Your Copilot draft will appear here.</div></section><aside class="commercial-panel dark"><span class="commercial-kicker">HUMAN GOVERNANCE</span><h2>Teacher approval remains mandatory</h2><p>Copilot prepares drafts. It does not publish material, issue high-stakes grades or make irreversible learner decisions automatically.</p><div class="commercial-info-list"><div><small>Scope</small><strong>Current school · Grades 8–12</strong></div><div><small>Review</small><strong>Curriculum accuracy, accessibility and learner suitability</strong></div><div><small>Auditability</small><strong>Saved drafts retain grade, subject, task and creation context</strong></div></div></aside></div></div>`;
    page.querySelector('[data-commercial-back]')?.addEventListener('click',backToWorkspace);
    page.querySelector<HTMLSelectElement>('[data-grade]')?.addEventListener('change',e=>{grade=(e.target as HTMLSelectElement).value;subject=subjectsForGrade(grade)[0];draw();});
    page.querySelector<HTMLSelectElement>('[data-subject]')?.addEventListener('change',e=>{subject=(e.target as HTMLSelectElement).value;});
    page.querySelector<HTMLFormElement>('[data-copilot-form]')?.addEventListener('submit',async e=>{e.preventDefault();const task=page.querySelector<HTMLSelectElement>('[data-task]')?.value||'Lesson plan';const focus=page.querySelector<HTMLTextAreaElement>('[data-focus]')?.value.trim()||'Core curriculum concept';const holder=page.querySelector<HTMLElement>('[data-output]');if(!holder)return;holder.textContent='Generating teacher-reviewed draft…';let reply='';try{reply=await askAI(`You are Teacher Copilot inside EduPath AI. Prepare an editable ${task} for ${grade} ${subject}. Focus: ${focus}. Include learning intention, prerequisite knowledge, teacher modelling, guided practice, differentiated support, independent practice, formative assessment, common misconceptions, accessibility considerations and a teacher review checklist. Nothing is published automatically. Use interface language code ${currentLanguage()}.`);}catch{reply=copilotFallback(task,grade,subject,focus);}holder.innerHTML=`<strong>${esc(task)} · ${esc(grade)} ${esc(subject)}</strong><div style="margin-top:10px">${esc(reply).replace(/\n/g,'<br>')}</div><div class="commercial-toolbar" style="margin-top:16px"><button class="commercial-btn" data-copy type="button">Copy draft</button><button class="commercial-btn primary" data-save type="button">Save unpublished draft</button></div>`;holder.querySelector('[data-copy]')?.addEventListener('click',()=>navigator.clipboard?.writeText(reply));holder.querySelector('[data-save]')?.addEventListener('click',()=>{let list:any[]=[];try{list=JSON.parse(localStorage.getItem('edupath.demo.materials.v1')||'[]');}catch{}list.unshift({id:`commercial-copilot-${Date.now()}`,title:`${task}: ${focus.slice(0,52)}`,grade,subject,type:'Teacher Copilot draft',body:reply,published:false,createdAt:new Date().toISOString().slice(0,10)});localStorage.setItem('edupath.demo.materials.v1',JSON.stringify(list));holder.insertAdjacentHTML('beforeend','<p><b>Saved:</b> unpublished teacher material. Review before publishing.</p>');});});
  };draw();
}

function ensureFeatureNav(){
  const aside=document.querySelector<HTMLElement>('.app-shell aside');if(!aside)return;assignNavKeys();const r=currentRole();
  const needed:{key:string,id:string,roles:Role[]}[]=[{key:'Student GPT',id:'student-gpt',roles:['Learner']},{key:'Parent GPT',id:'parent-gpt',roles:['Parent / Guardian']}];
  needed.forEach(item=>{
    const existing=buttonFor(item.key);
    const fallback=aside.querySelector<HTMLButtonElement>(`[data-commercial-nav="${item.id}"]`);
    if(!item.roles.includes(r)){fallback?.remove();return;}
    if(existing&&existing!==fallback){fallback?.remove();return;}
    if(fallback)return;
    const button=document.createElement('button');button.type='button';button.className='commercial-feature-nav';button.dataset.commercialNav=item.id;button.dataset.navKey=item.key;button.innerHTML=`<span>✦</span><span>${esc(item.key)}</span>`;const footer=aside.querySelector('.side-footer');footer?aside.insertBefore(button,footer):aside.appendChild(button);
  });
}

function detailFor(label:string):DetailModel{
  const low=label.toLowerCase();const r=currentRole();const page=document.querySelector<HTMLElement>('.app-shell main h1,.learning-suite-page:not([hidden]) h1,.wc-page:not([hidden]) h1,.fx-page:not([hidden]) h1')?.textContent?.trim()||'Workspace';
  if(/geometry|parallel|corresponding|alternate|angle|algebra|equation/.test(low))return{title:label,summary:'This learning item is part of the learner’s current mathematics pathway. It should connect concept knowledge, worked reasoning, practice evidence and the next remediation or progression step.',facts:['Current demo mathematics performance: 71%','Current geometry mastery: 68% and improving','Prerequisite focus: parallel lines, transversals and angle relationships','Evidence sources: formative checks, teacher feedback and learning activity history'],actions:['Open Student GPT for a step-by-step explanation','Use the Learning Hub resource for the topic','Complete a short formative check','Escalate to the teacher if the misconception persists']};
  if(/assignment|worksheet|essay|submission|task|due|mark/.test(low))return{title:label,summary:'Assignment detail combines due status, submission evidence, teacher feedback and the next required learner or teacher action.',facts:['Submission status is shown separately from AI guidance','Teacher feedback remains the authoritative review record','Late or incomplete work can trigger a support workflow, not an automatic penalty','Guardian views only show information linked to their learner'],actions:['Open the assignment instructions','Review rubric or success criteria','Submit or resubmit where permitted','Review teacher feedback and next steps']};
  if(/assessment|formative|result|reviewed|score|practice|exam/.test(low))return{title:label,summary:'Assessment detail should show the selected grade and subject, attempt evidence, verified result, feedback and any authorised retry or remediation pathway.',facts:['AI-generated guidance is separated from educator-verified results','High-stakes grading is not autonomous','Practice activities may use guided solutions where appropriate','Proctoring signals require human review'],actions:['Review question-level feedback','Revisit prerequisite learning where required','Use Exam Practice for another attempt','Ask the teacher about verified results or retry rules']};
  if(/attendance|late|absence|absent/.test(low))return{title:label,summary:'Attendance is treated as a support signal. EduPath shows the pattern, period and follow-up status without inferring sensitive reasons for absence.',facts:['Learner demo attendance: 94% this term','Teacher dashboard demo average: 92% across classes','Repeated patterns require human review','No automatic disciplinary conclusion is generated'],actions:['Review the attendance timeline','Confirm data accuracy','Contact the authorised guardian where appropriate','Create a support intervention only after human review']};
  if(/intervention|support|remediation|needs support|follow-up/.test(low))return{title:label,summary:'Interventions are human-owned support workflows with evidence, an accountable owner, review date, status and outcome.',facts:['AI may recommend an intervention but cannot approve it','Evidence should explain why support is recommended','Teacher or authorised support staff own the action','Closure requires a recorded outcome'],actions:['Review the evidence','Assign or confirm the intervention owner','Select the support activity','Set a review point and record the outcome']};
  if(/class|grade 8|grade 9|grade 10|grade 11|grade 12/.test(low)&&r==='Teacher')return{title:label,summary:'Class detail provides attendance, curriculum coverage, assignment status, assessment trends and learners requiring authorised support.',facts:['The demo teacher is scoped to a high-school institution','Only authorised classes and Grades 8–12 are visible','Class trends are contextual indicators, not educator rankings','Learner-level drill-downs follow role permissions'],actions:['Open the class roster','Review subject and curriculum progress','Inspect learners needing support','Publish or review the next learning activity']};
  if(/digital|device|connect|offline|inclusion/.test(low))return{title:label,summary:'Digital inclusion intelligence shows whether connectivity, device access, offline use or accessibility constraints could affect learning access.',facts:['Connectivity, device and offline-use indicators are kept distinct','Constraints should not be used to penalise learners or schools','Offline learning is a supported delivery mode','Infrastructure actions need an accountable owner'],actions:['Identify the affected cohort or school','Separate device, connectivity and power constraints','Prepare an offline or shared-device support option','Track infrastructure follow-up to resolution']};
  if(/curriculum|coverage|subject|mathematics|english|science|geography|history|accounting|business|economics/.test(low))return{title:label,summary:'Curriculum detail connects the authorised grade and subject to learning outcomes, teacher-published resources, assessment evidence and progression support.',facts:[`Current workspace: ${page}`,'Institution scope determines which grades and subjects are displayed','Official curriculum packs require provenance and approval','Student GPT should remain grounded to the selected grade and subject context'],actions:['Open the curriculum pathway','Review approved learning material','Inspect assessment evidence','Identify gaps in coverage or prerequisite knowledge']};
  if(/teacher|educator|moderation|timetable/.test(low))return{title:label,summary:'Teacher operational detail supports workload, curriculum delivery, moderation and learner-support coordination without reducing educator performance to a single score.',facts:['School leaders see authorised school-level information','Workload and support signals require context','Moderation and curriculum coverage remain professional responsibilities','AI recommendations require educator judgement'],actions:['Open the relevant teaching or moderation item','Review capacity and timetable context','Assign support where required','Record completion or escalation']};
  if(/school|district|province|region/.test(low))return{title:label,summary:'System-level detail combines academic progress, attendance, interventions, curriculum delivery and digital inclusion so leaders can target support with context.',facts:['Views are scoped by authorised institution or geography','Aggregated indicators should preserve underlying evidence','Comparisons should not become context-free league tables','Synthetic demo values are used in the hackathon build'],actions:['Drill down by authorised grade and subject','Review unresolved interventions','Check digital-inclusion constraints','Assign and track a support action']};
  if(/audit|system health|user|role|security|data|sync/.test(low))return{title:label,summary:'Platform administration detail covers identity, access, auditability, service health, data controls and accountable operational follow-up.',facts:['Least privilege and role scoping are required','Audit events should record actor, action, object and outcome','Secrets must stay server-side','Commercial deployment requires server-validated identity and tenant controls'],actions:['Inspect the relevant operational record','Validate permissions before making changes','Review audit evidence','Escalate unresolved service or security issues']};
  const roleSummary:Record<Role,string>={Learner:'This item should help the learner understand what to do next, what evidence is available and where to get support.',Teacher:'This item should provide class or learner context, evidence, accountable next actions and curriculum relevance.', 'Parent / Guardian':'This item is filtered to the linked learner and should explain progress, challenge areas and practical support options without exposing confidential notes.','Principal / School Administrator':'This item should support school-level oversight across authorised grades and subjects, including progress, attendance, interventions and digital inclusion.','District Official':'This item should support evidence-based cross-school assistance and accountable follow-through.','Provincial Official':'This item should support contextual district and school intelligence, intervention portfolios and inclusion priorities.','National Education Analyst':'This item should present aggregated evidence, data limitations and decision-support context.','Platform Administrator':'This item should expose the operational configuration, access control, audit and service-health context required for administration.','Support Administrator':'This item should provide safe diagnostic information, user impact and an auditable resolution path.'};
  return{title:label,summary:roleSummary[r],facts:[`Current workspace: ${page}`,`Role scope: ${r}`,'The detail view uses synthetic hackathon data unless a governed source system is connected','Consequential actions require the appropriate authorised human owner'],actions:['Review the available evidence','Open the relevant authorised record or workflow','Confirm the accountable next action','Record the outcome or escalate when needed']};
}
function showDetail(label:string){
  const model=detailFor(label);let drawer=document.querySelector<HTMLElement>('.commercial-detail-drawer');if(!drawer){drawer=document.createElement('aside');drawer.className='commercial-detail-drawer';drawer.innerHTML='<div class="commercial-detail-head"><div><span>EDUPATH DETAIL</span><h2 data-detail-title>Details</h2></div><button class="commercial-detail-close" type="button" aria-label="Close details">×</button></div><div class="commercial-detail-body" data-detail-body></div>';document.body.appendChild(drawer);drawer.querySelector('.commercial-detail-close')?.addEventListener('click',()=>drawer?.classList.remove('open'));}
  const title=drawer.querySelector<HTMLElement>('[data-detail-title]');const body=drawer.querySelector<HTMLElement>('[data-detail-body]');if(title)title.textContent=model.title;if(body)body.innerHTML=`<p>${esc(model.summary)}</p><section class="commercial-detail-section"><h3>Relevant information</h3><ul>${model.facts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="commercial-detail-section"><h3>Recommended next actions</h3><div class="commercial-detail-actions">${model.actions.map(x=>`<div>${esc(x)}</div>`).join('')}</div></section>`;drawer.classList.add('open');
}

function wireCommercialRouting(){
  document.addEventListener('click',event=>{
    const target=event.target as HTMLElement;
    const route=target.closest<HTMLElement>('[data-route],[data-jump]');
    if(route){const key=route.dataset.route||route.dataset.jump||'';const nav=buttonFor(key);if(nav){event.preventDefault();event.stopImmediatePropagation();nav.click();return;}}
    const button=target.closest<HTMLButtonElement>('.app-shell aside button');if(!button)return;
    stabilizeRole();assignNavKeys();const key=button.dataset.navKey||cleanNavText(button.textContent||'');
    if(key==='Student GPT'&&currentRole()==='Learner'){event.preventDefault();event.stopImmediatePropagation();document.querySelectorAll('.app-shell aside button').forEach(b=>b.classList.remove('active'));button.classList.add('active');openFeature('student-gpt');return;}
    if(key==='Parent GPT'&&currentRole()==='Parent / Guardian'){event.preventDefault();event.stopImmediatePropagation();document.querySelectorAll('.app-shell aside button').forEach(b=>b.classList.remove('active'));button.classList.add('active');openFeature('parent-gpt');return;}
    if(key==='Teacher Copilot'&&currentRole()==='Teacher'){event.preventDefault();event.stopImmediatePropagation();document.querySelectorAll('.app-shell aside button').forEach(b=>b.classList.remove('active'));button.classList.add('active');openFeature('teacher-copilot');return;}
    resetWorkspace();
  },true);
  window.addEventListener('edupath:detail-request',event=>{event.stopImmediatePropagation();const label=(event as CustomEvent<{label?:string}>).detail?.label||'Details';showDetail(label);},true);
}

function healthSweep(){stabilizeRole();assignNavKeys();dedupeDynamicPages();ensureFeatureNav();}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;healthSweep();});}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});
window.addEventListener('edupath:languagechange',()=>window.setTimeout(()=>{assignNavKeys();ensureFeatureNav();},0));
wireCommercialRouting();schedule();

(window as any).EduPathNavigationDiagnostics={run:()=>{healthSweep();return{role:currentRole(),learningSuitePages:document.querySelectorAll('.learning-suite-page').length,examPracticePages:document.querySelectorAll('.exam-practice-page').length,agentCentrePages:document.querySelectorAll('.agent-centre-page').length,featurePages:document.querySelectorAll('.commercial-feature-page').length,visibleOverlays:[...document.querySelectorAll<HTMLElement>('.learning-suite-page,.exam-practice-page,.agent-centre-page,.wc-page,.fx-page,.ai-settings-page,.commercial-feature-page')].filter(x=>!x.hidden&&x.offsetParent!==null).map(x=>x.className)}};
