import './worldclass-platform.css';

type Role = 'Learner'|'Teacher'|'Parent / Guardian'|'Principal / School Administrator'|'District Official'|'Provincial Official'|'National Education Analyst'|'Platform Administrator'|'Support Administrator';
type AuditEvent={time:string;actor:string;role:string;action:string;result:string;detail:string};

const GRADES=['Grade R','Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6','Grade 7','Grade 8','Grade 9','Grade 10','Grade 11','Grade 12'];
const SUBJECTS=[
'Home Language','First Additional Language','Second Additional Language','Mathematics','Mathematical Literacy','Life Skills','Life Orientation','Natural Sciences','Natural Sciences and Technology','Technology','Social Sciences','Creative Arts','Economic and Management Sciences','Physical Sciences','Life Sciences','Geography','History','Accounting','Business Studies','Economics','Agricultural Sciences','Agricultural Management Practices','Agricultural Technology','Civil Technology','Electrical Technology','Mechanical Technology','Engineering Graphics and Design','Computer Applications Technology','Information Technology','Tourism','Hospitality Studies','Consumer Studies','Design','Dance Studies','Dramatic Arts','Music','Visual Arts','Religion Studies','Marine Sciences','Technical Mathematics','Technical Sciences'
];
const LANG_KEY='edupath.language.v1';
const AUDIT_KEY='edupath.audit.v2';
const STUDENTS_KEY='edupath.students.v1';
const CAREER_KEY='edupath.career.progress.v1';
const localOnlyNotice='Local-only mode keeps selected exam papers and answer books on this device. Nothing is uploaded unless the learner explicitly chooses a cloud workflow.';

const pages=[
  {id:'curriculum',label:'Curriculum R–12',roles:['Learner','Teacher','Parent / Guardian','Principal / School Administrator','District Official','Provincial Official','National Education Analyst','Platform Administrator']},
  {id:'proctoring',label:'Proctored Exams',roles:['Learner','Teacher','Principal / School Administrator','Platform Administrator','Support Administrator']},
  {id:'students',label:'Student Management',roles:['Teacher','Principal / School Administrator','District Official','Provincial Official','Platform Administrator','Support Administrator']},
  {id:'career',label:'Career Readiness',roles:['Learner','Teacher','Parent / Guardian','Principal / School Administrator','District Official','Provincial Official','National Education Analyst']},
  {id:'reports',label:'Reports & User Logs',roles:['Teacher','Principal / School Administrator','District Official','Provincial Official','National Education Analyst','Platform Administrator','Support Administrator']},
  {id:'sovereignty',label:'Security & Data Sovereignty',roles:['Principal / School Administrator','District Official','Provincial Official','National Education Analyst','Platform Administrator','Support Administrator']}
];

function role():Role{return (document.querySelector('.userbox small')?.textContent?.trim()||'Learner') as Role;}
function actor(){return document.querySelector('.userbox strong')?.textContent?.trim()||'Demo User';}
function esc(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
function log(action:string,result='Success',detail=''){
  const events=JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]') as AuditEvent[];
  events.unshift({time:new Date().toISOString(),actor:actor(),role:role(),action,result,detail});
  localStorage.setItem(AUDIT_KEY,JSON.stringify(events.slice(0,500)));
}
function toast(msg:string){let n=document.querySelector<HTMLElement>('.wc-toast');if(!n){n=document.createElement('div');n.className='wc-toast';document.body.appendChild(n);}n.textContent=msg;n.classList.add('show');setTimeout(()=>n?.classList.remove('show'),2200);}

function pageShell(title:string,eyebrow:string,body:string){return `<div class="wc-inner"><div class="wc-head"><div><span>${eyebrow}</span><h1>${title}</h1><p>${body}</p></div><button data-wc-back class="wc-btn secondary">Back to workspace</button></div><div data-wc-body></div></div>`;}
function mountPage(id:string){
  const shell=document.querySelector<HTMLElement>('.app-shell'); if(!shell)return;
  document.querySelectorAll<HTMLElement>('.wc-page,.agent-centre-page,.learning-suite-page,.exam-practice-page').forEach(p=>p.hidden=true);
  const main=shell.querySelector<HTMLElement>('main'); if(main)main.style.display='none';
  let page=shell.querySelector<HTMLElement>(`[data-wc-page="${id}"]`);
  if(!page){page=document.createElement('section');page.className='wc-page';page.dataset.wcPage=id;shell.appendChild(page);} page.hidden=false;
  if(id==='curriculum')renderCurriculum(page); if(id==='proctoring')renderProctoring(page); if(id==='students')renderStudents(page); if(id==='career')renderCareer(page); if(id==='reports')renderReports(page); if(id==='sovereignty')renderSovereignty(page);
  log('Open module','Success',id); window.scrollTo({top:0,behavior:'smooth'});
}
function closePages(){document.querySelectorAll<HTMLElement>('.wc-page').forEach(p=>p.hidden=true);const main=document.querySelector<HTMLElement>('.app-shell main');if(main)main.style.display='block';}

function renderCurriculum(page:HTMLElement){
  page.innerHTML=pageShell('Curriculum R–12','FULL LEARNING CATALOGUE','A configurable curriculum catalogue covering Grade R to Grade 12 and the full subject taxonomy, with approved content packs attached per grade and subject.');
  const body=page.querySelector<HTMLElement>('[data-wc-body]')!;
  body.innerHTML=`<section class="wc-stats"><article><strong>${GRADES.length}</strong><span>Grades</span></article><article><strong>${SUBJECTS.length}</strong><span>Subject families</span></article><article><strong>11</strong><span>Platform languages</span></article><article><strong>Governed</strong><span>Content provenance</span></article></section>
  <section class="wc-panel"><div class="wc-controls"><label>Grade<select data-grade>${GRADES.map(g=>`<option>${g}</option>`).join('')}</select></label><label>Subject<select data-subject>${SUBJECTS.map(s=>`<option>${s}</option>`).join('')}</select></label><button class="wc-btn primary" data-open-subject>Open learning pathway</button></div><div data-curriculum-result class="wc-result"><h2>Select a grade and subject</h2><p>EduPath will open a distinct learning pathway page with lessons, teacher material, assessments, Student GPT and exam practice links for that selection.</p></div></section>`;
  body.querySelector('[data-open-subject]')?.addEventListener('click',()=>{const g=(body.querySelector('[data-grade]') as HTMLSelectElement).value;const s=(body.querySelector('[data-subject]') as HTMLSelectElement).value;const r=body.querySelector<HTMLElement>('[data-curriculum-result]')!;r.innerHTML=`<div class="wc-path-head"><span>${esc(g)}</span><h2>${esc(s)}</h2></div><div class="wc-actions"><button data-jump="Student GPT">Ask Student GPT</button><button data-jump="Learning Hub">Open LMS material</button><button data-jump="Exam Practice">Practice papers</button><button data-expand>View curriculum outcomes</button></div><div class="wc-expand" hidden data-expand-panel><h3>Configured pathway structure</h3><ol><li>Curriculum outcomes and prerequisites</li><li>Teacher-approved study materials</li><li>Adaptive learning activities and formative checks</li><li>Student GPT support grounded in the selected curriculum pack</li><li>Assessment and exam-practice evidence</li></ol><p><strong>Important:</strong> subject coverage is commercially configurable. Official curriculum packs must be loaded and reviewed by authorised curriculum owners before production use.</p></div>`;bindDynamicActions(r);log('Open curriculum pathway','Success',`${g} · ${s}`);});
}

function renderProctoring(page:HTMLElement){
  page.innerHTML=pageShell('Proctored Exams','PRIVACY-AWARE EXAM INTEGRITY','Camera-assisted invigilation with explicit consent, transparent event logging and a review report. Signals are evidence for a human reviewer, not automatic proof of misconduct.');
  const body=page.querySelector<HTMLElement>('[data-wc-body]')!;
  body.innerHTML=`<div class="proctor-grid"><section class="wc-panel"><div class="camera-wrap"><video data-camera playsinline muted></video><div class="camera-placeholder" data-camera-placeholder>Camera not started</div></div><div class="consent-box"><label><input type="checkbox" data-proctor-consent/> I consent to camera monitoring for this exam session and understand what will be recorded.</label></div><div class="wc-actions"><button class="wc-btn primary" data-start-proctor>Start proctored session</button><button class="wc-btn danger" data-stop-proctor disabled>End session & generate report</button></div><p class="privacy-note">Video stays in the live browser session in this demo. The report records session events such as camera availability, tab visibility, focus changes and fullscreen exits. It does not label a learner as cheating.</p></section><section class="wc-panel"><h2>Session integrity timeline</h2><div class="timeline" data-proctor-log><p>No events yet.</p></div><div class="wc-actions"><button data-download-report class="wc-btn secondary" disabled>Download integrity report</button></div></section></div>`;
  let stream:MediaStream|null=null; const events:{time:string;type:string;detail:string}[]=[]; let active=false;
  const add=(type:string,detail:string)=>{events.push({time:new Date().toISOString(),type,detail});const holder=body.querySelector<HTMLElement>('[data-proctor-log]')!;holder.innerHTML=events.map(e=>`<div class="timeline-row"><time>${new Date(e.time).toLocaleTimeString()}</time><strong>${esc(e.type)}</strong><span>${esc(e.detail)}</span></div>`).join('');};
  const visibility=()=>{if(active)add('Visibility change',document.hidden?'Exam tab hidden':'Exam tab visible');}; const blur=()=>{if(active)add('Window focus','Exam window lost focus');}; const full=()=>{if(active&&!document.fullscreenElement)add('Fullscreen','Fullscreen exited');};
  body.querySelector('[data-start-proctor]')?.addEventListener('click',async()=>{const consent=(body.querySelector('[data-proctor-consent]') as HTMLInputElement).checked;if(!consent){toast('Consent is required before camera monitoring starts.');return;}try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});const video=body.querySelector<HTMLVideoElement>('[data-camera]')!;video.srcObject=stream;await video.play();body.querySelector<HTMLElement>('[data-camera-placeholder]')!.hidden=true;active=true;add('Session','Proctored session started');document.addEventListener('visibilitychange',visibility);window.addEventListener('blur',blur);document.addEventListener('fullscreenchange',full);(body.querySelector('[data-start-proctor]') as HTMLButtonElement).disabled=true;(body.querySelector('[data-stop-proctor]') as HTMLButtonElement).disabled=false;log('Start proctored exam','Success','Camera permission granted');}catch(e){add('Camera','Camera unavailable or permission denied');toast('Camera access was not granted.');log('Start proctored exam','Denied','Camera unavailable');}});
  body.querySelector('[data-stop-proctor]')?.addEventListener('click',()=>{active=false;stream?.getTracks().forEach(t=>t.stop());add('Session','Proctored session ended');document.removeEventListener('visibilitychange',visibility);window.removeEventListener('blur',blur);document.removeEventListener('fullscreenchange',full);(body.querySelector('[data-download-report]') as HTMLButtonElement).disabled=false;(body.querySelector('[data-stop-proctor]') as HTMLButtonElement).disabled=true;log('End proctored exam','Success',`${events.length} integrity events`);});
  body.querySelector('[data-download-report]')?.addEventListener('click',()=>{const report={student:actor(),role:role(),generatedAt:new Date().toISOString(),notice:'Behavioral signals require human review and are not proof of misconduct.',events};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='edupath-proctoring-report.json';a.click();URL.revokeObjectURL(a.href);log('Download proctoring report');});
}

function seedStudents(){return [{id:'STU-1001',name:'Thando Mokoena',grade:'Grade 9',school:'EduPath Demo School',status:'Active',attendance:'94%',progress:'74%'},{id:'STU-1002',name:'Anele Dube',grade:'Grade 9',school:'EduPath Demo School',status:'Active',attendance:'86%',progress:'68%'},{id:'STU-1003',name:'Kagiso Molefe',grade:'Grade 8',school:'EduPath Demo School',status:'Support',attendance:'91%',progress:'66%'}];}
function renderStudents(page:HTMLElement){
  let students=JSON.parse(localStorage.getItem(STUDENTS_KEY)||'null')||seedStudents();localStorage.setItem(STUDENTS_KEY,JSON.stringify(students));
  page.innerHTML=pageShell('Student Management','LEARNER OPERATIONS','Role-scoped student records with enrolment, progress, attendance and support visibility.');const body=page.querySelector<HTMLElement>('[data-wc-body]')!;
  const draw=()=>{body.innerHTML=`<section class="wc-stats"><article><strong>${students.length}</strong><span>Students</span></article><article><strong>${students.filter((s:any)=>s.status==='Active').length}</strong><span>Active</span></article><article><strong>${students.filter((s:any)=>s.status==='Support').length}</strong><span>Support cases</span></article><article><strong>RBAC</strong><span>Scoped access</span></article></section><section class="wc-panel"><div class="wc-section-head"><h2>Student register</h2><button class="wc-btn primary" data-add-student>Add student</button></div><div class="student-table">${students.map((s:any)=>`<article><div><strong>${esc(s.name)}</strong><span>${esc(s.id)} · ${esc(s.grade)}</span></div><span>${esc(s.attendance)} attendance</span><span>${esc(s.progress)} progress</span><span class="status">${esc(s.status)}</span><button data-view-student="${s.id}">Open</button></article>`).join('')}</div><div data-student-detail></div></section>`;bind();};
  const bind=()=>{body.querySelector('[data-add-student]')?.addEventListener('click',()=>{const id=`STU-${1000+students.length+1}`;students.push({id,name:`Demo Student ${students.length+1}`,grade:'Grade 8',school:'EduPath Demo School',status:'Active',attendance:'100%',progress:'New'});localStorage.setItem(STUDENTS_KEY,JSON.stringify(students));log('Create student','Success',id);draw();});body.querySelectorAll<HTMLElement>('[data-view-student]').forEach(btn=>btn.addEventListener('click',()=>{const s=students.find((x:any)=>x.id===btn.dataset.viewStudent);const d=body.querySelector<HTMLElement>('[data-student-detail]')!;d.innerHTML=`<div class="student-detail"><h3>${esc(s.name)}</h3><p>${esc(s.grade)} · ${esc(s.school)}</p><div class="wc-actions"><button data-expand-profile>Expand learner profile</button><button data-expand-support>Expand support history</button><button data-expand-guardian>Expand guardian access</button></div><div class="wc-expand" data-profile-panel hidden><p>Academic progress: ${esc(s.progress)} · Attendance: ${esc(s.attendance)} · Status: ${esc(s.status)}</p></div></div>`;d.querySelector('[data-expand-profile]')?.addEventListener('click',()=>{const p=d.querySelector<HTMLElement>('[data-profile-panel]')!;p.hidden=!p.hidden;});log('Open student record','Success',s.id);});});};draw();
}

const careerTracks=[
  {title:'Digital Workplace Foundations',aud:'All school leavers',mods:['Productivity tools','Professional communication','Cyber hygiene','AI literacy','Digital collaboration']},
  {title:'Corporate Readiness',aud:'Private sector',mods:['CV and interview preparation','Workplace professionalism','Data and AI tools','Project fundamentals','Career pathways']},
  {title:'Public Sector Digital Literacy',aud:'Government',mods:['Digital public services','Information governance','Responsible AI','Records and audit','Citizen-centred service']},
  {title:'SME & Entrepreneurship',aud:'Small and medium enterprises',mods:['Digital commerce','Customer service','Financial basics','AI for micro-business','Cyber safety']},
  {title:'Strategic Talent Growth',aud:'Workplace progression',mods:['Leadership foundations','Problem solving','Data-informed decisions','Change readiness','Continuous learning']}
];
function renderCareer(page:HTMLElement){
  let progress=JSON.parse(localStorage.getItem(CAREER_KEY)||'{}');
  page.innerHTML=pageShell('Career Readiness & Workplace Services','POST-SCHOOL TRANSITION','A bridge from school learning into employment readiness, public-sector digital literacy, corporate pathways and SME capability.');const body=page.querySelector<HTMLElement>('[data-wc-body]')!;
  const draw=()=>{body.innerHTML=`<section class="workplace-banner"><div><span>AI-POWERED INDUSTRY TRAINING ENGINE</span><h2>Learn → Prove skills → Prepare for work</h2><p>Personalised workplace pathways continue the learner journey beyond Grade 12.</p></div></section><section class="career-grid">${careerTracks.map((t,i)=>`<article class="wc-panel"><span class="career-aud">${esc(t.aud)}</span><h3>${esc(t.title)}</h3><div class="progress"><i style="width:${progress[i]||0}%"></i></div><strong>${progress[i]||0}% complete</strong><div class="wc-actions"><button data-career="${i}">Open pathway</button><button data-career-progress="${i}">Complete next module</button></div><div class="wc-expand" data-career-panel="${i}" hidden><ol>${t.mods.map(m=>`<li>${esc(m)}</li>`).join('')}</ol></div></article>`).join('')}</section><section class="wc-panel"><h2>Workplace analytics</h2><div class="wc-stats compact"><article><strong>Skills</strong><span>Badges & mastery</span></article><article><strong>ROI</strong><span>Training outcomes</span></article><article><strong>Audit</strong><span>Completion evidence</span></article><article><strong>Paths</strong><span>Corporate · Public · SME</span></article></div></section>`;bind();};
  const bind=()=>{body.querySelectorAll<HTMLElement>('[data-career]').forEach(b=>b.addEventListener('click',()=>{const p=body.querySelector<HTMLElement>(`[data-career-panel="${b.dataset.career}"]`)!;p.hidden=!p.hidden;}));body.querySelectorAll<HTMLElement>('[data-career-progress]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.careerProgress);progress[i]=Math.min(100,(progress[i]||0)+20);localStorage.setItem(CAREER_KEY,JSON.stringify(progress));log('Career training progress','Success',careerTracks[i].title);draw();}));};draw();
}

function renderReports(page:HTMLElement){
  page.innerHTML=pageShell('Reports & User Logs','OPERATIONAL INTELLIGENCE','Auditable reporting for learning, access, agents, exams, training, support and user activity.');const body=page.querySelector<HTMLElement>('[data-wc-body]')!;const events=JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]') as AuditEvent[];
  body.innerHTML=`<section class="wc-stats"><article><strong>${events.length}</strong><span>User log events</span></article><article><strong>${new Set(events.map(e=>e.actor)).size||1}</strong><span>Actors</span></article><article><strong>${events.filter(e=>e.action.toLowerCase().includes('exam')).length}</strong><span>Exam events</span></article><article><strong>${events.filter(e=>e.action.toLowerCase().includes('career')).length}</strong><span>Training events</span></article></section><section class="wc-panel"><div class="wc-section-head"><h2>Activity log</h2><div class="wc-actions"><button data-export-log>Export JSON</button><button data-clear-log>Clear demo log</button></div></div><div class="audit-table">${events.length?events.slice(0,100).map(e=>`<article><time>${new Date(e.time).toLocaleString()}</time><strong>${esc(e.action)}</strong><span>${esc(e.actor)} · ${esc(e.role)}</span><em>${esc(e.result)}</em><small>${esc(e.detail)}</small></article>`).join(''):'<p>No demo activity recorded yet.</p>'}</div></section>`;
  body.querySelector('[data-export-log]')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(events,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='edupath-user-audit-log.json';a.click();URL.revokeObjectURL(a.href);});body.querySelector('[data-clear-log]')?.addEventListener('click',()=>{localStorage.removeItem(AUDIT_KEY);toast('Demo audit log cleared.');renderReports(page);});
}

function renderSovereignty(page:HTMLElement){
  page.innerHTML=pageShell('Security & Data Sovereignty','COMMERCIAL DEPLOYMENT CONTROLS','Deployment patterns designed for least privilege, jurisdictional control, local storage options, auditability and customer-controlled data residency.');const body=page.querySelector<HTMLElement>('[data-wc-body]')!;
  body.innerHTML=`<section class="sovereignty-grid"><article class="wc-panel"><h2>Data residency profiles</h2><div class="option-card"><strong>School / institution hosted</strong><p>Customer-managed deployment inside an approved jurisdiction or private environment.</p></div><div class="option-card"><strong>Regional cloud</strong><p>Tenant data pinned to approved regional infrastructure with documented sub-processors and transfer controls.</p></div><div class="option-card"><strong>Local-only exam mode</strong><p>${localOnlyNotice}</p></div></article><article class="wc-panel"><h2>Security baseline</h2><ul class="security-list"><li>Server-side RBAC/ABAC and least privilege</li><li>MFA-ready staff and administrator access</li><li>Encryption in transit and at rest</li><li>Tenant, school, district and jurisdiction scoping</li><li>Consent and purpose limitation for child data</li><li>Immutable/auditable security event design</li><li>Restricted exports and role-based reporting</li><li>Secrets management and environment isolation</li><li>Data retention, deletion and legal-hold policies</li><li>Human review for consequential AI actions</li></ul></article></section><section class="wc-panel"><h2>Commercial readiness checklist</h2><div class="readiness-grid">${['Identity federation','Tenant isolation','Data residency policy','Backup & disaster recovery','SIEM integration','Penetration testing','DPIA / privacy review','Accessibility validation','Model governance','Incident response','SLA / observability','Curriculum licensing'].map(x=>`<div><span>◌</span><strong>${x}</strong><small>Production configuration / validation required</small></div>`).join('')}</div><p class="privacy-note">This hackathon build demonstrates the architecture and controls. Legal, regulatory, security and curriculum compliance must be validated for each production jurisdiction and customer deployment.</p></section>`;
}

function bindDynamicActions(root:ParentNode){root.querySelectorAll<HTMLElement>('[data-expand]').forEach(b=>b.addEventListener('click',()=>{const p=root.querySelector<HTMLElement>('[data-expand-panel]');if(p)p.hidden=!p.hidden;}));root.querySelectorAll<HTMLElement>('[data-jump]').forEach(b=>b.addEventListener('click',()=>{const label=b.dataset.jump||'';const side=[...document.querySelectorAll<HTMLButtonElement>('aside button')].find(x=>x.textContent?.trim()===label);if(side){closePages();side.click();}else toast(`${label} is available from the learner workspace.`);}));}

function injectNav(){const aside=document.querySelector<HTMLElement>('.app-shell aside');if(!aside||aside.querySelector('[data-wc-nav]'))return;const footer=aside.querySelector('.side-footer');const block=document.createElement('div');block.dataset.wcNav='true';block.className='wc-nav-block';block.innerHTML=`<div class="side-label">FUTURE-READY</div>${pages.filter(p=>p.roles.includes(role())).map(p=>`<button type="button" data-wc-open="${p.id}">${p.label}</button>`).join('')}`;footer?aside.insertBefore(block,footer):aside.appendChild(block);block.querySelectorAll<HTMLElement>('[data-wc-open]').forEach(b=>b.addEventListener('click',()=>mountPage(b.dataset.wcOpen||'')));}

function wireGlobal(){document.addEventListener('click',e=>{const target=e.target as HTMLElement;if(target.closest('[data-wc-back]'))closePages();const ordinary=target.closest<HTMLButtonElement>('aside button:not([data-wc-open])');if(ordinary&&!ordinary.closest('[data-wc-nav]'))closePages();});}
function init(){injectNav();wireGlobal();const observer=new MutationObserver(()=>injectNav());observer.observe(document.body,{childList:true,subtree:true});}
init();
